### ISSUE TITLE
Add windows compatibility

### ISSUE THREAD

**Issue by Syycorax** [Tim-ats-d/Visual-dialog#7]
:croissant:

**Comment by The-ZmaZe** [comment]
![](https://github.githubassets.com/images/icons/emoji/unicode/1f950.png)

**Comment by quentinguidee** [comment]
Sweaty windows user :trollface:

**Comment by The-ZmaZe** [comment]
add unix compatibility to windows

**Comment by quentinguidee** [comment]
_Beautiful_ dialog boxes on Windows would be somewhat paradoxical 👁️

**Comment by The-ZmaZe** [comment]
@quentinguidee lol

**Comment by Guiguim255** [comment]
@quentinguidee Yeah and if it becomes fully cross-platform it could be disturbing for MacOS users, we should keep it in a small closed ecosystem ⛓

**Comment by quentinguidee** [comment]
@Guiguim255 I totally agree

**Comment by quentinguidee** [comment]
Guiguim president!

**Comment by Guiguim255** [comment]
President of Belgium

**Comment by Tim-ats-d** [comment]
To install curses on Windows, you just need `windows-curses` module:
```
pip install curses-windows
```
